void get_processor_id() {}
void get_processor_acpi_id() {}
void get_active_cpu_count() {}
void get_cpu_extended_info() {}
void update_cpu_speed() {}
void set_cpu_time_handler() {}
void reboot() {}
void apm_poweroff() {}
void get_app_server_port() {}
void sys_get_app_server_port() {}
void get_system_path() {}
void sys_get_system_path() {}
void get_system_time() {}
void get_real_time() {}
void get_idle_time() {}
void sys_GetTime() {}
void sys_SetTime() {}
void set_idle_loop_handler() {}
void get_system_info() {}
void sys_get_process_id() {}
void sys_wait4() {}
void sys_wait_for_thread() {}
void sys_waitpid() {}
void setgid() {}
void setpgid() {}
void setsid() {}
void setuid() {}
void getegid() {}
void geteuid() {}
void getgid() {}
void getuid() {}
void getfsgid() {}
void getfsuid() {}
void getgroups() {}
void getpgid() {}
void getpgrp() {}
void getppid() {}
void getsid() {}
void sys_kill() {}
void sys_kill_proc() {}
void sys_killpg() {}
void sys_exit() {}
void spawn_kernel_thread() {}
void start_thread() {}
void stop_thread() {}
void sys_suspend_thread() {}
void sys_rename_thread() {}
void sys_resume_thread() {}
void sys_get_thread_id() {}
void sys_get_thread_info() {}
void sys_get_thread_proc() {}
void suspend() {}
void snooze() {}
void wakeup_thread() {}
void set_thread_priority() {}
void set_thread_target_cpu() {}
void Schedule() {}
void sleep_on_queue() {}
void wake_up_sleepers() {}
void is_signal_pending() {}
void get_signal_mode() {}
void sys_sigaction() {}
void load_kernel_driver() {}
void unload_kernel_driver() {}
void open_image_file() {}
void get_symbol_by_address() {}
void get_image_info() {}
void get_symbol_address() {}
void print_registers() {}
void trace_stack() {}
void register_debug_cmd() {}
void sys_debug_read() {}
void sys_debug_write() {}
void panic() {}
void printk() {}
void dbprintf() {}
void isa_readb() {}
void isa_readl() {}
void isa_readw() {}
void isa_writeb() {}
void isa_writel() {}
void isa_writew() {}
void cli() {}
void sti() {}
void get_cpu_flags() {}
void put_cpu_flags() {}
void realint() {}
void request_irq() {}
void release_irq() {}
void enable_irq() {}
void disable_irq_nosync() {}
void request_dma() {}
void free_dma() {}
void enable_dma_channel() {}
void disable_dma_channel() {}
void clear_dma_ff() {}
void set_dma_mode() {}
void set_dma_page() {}
void set_dma_address() {}
void set_dma_count() {}
void create_timer() {}
void start_timer() {}
void delete_timer() {}
void create_semaphore() {}
void delete_semaphore() {}
void lock_semaphore_ex() {}
void lock_mutex() {}
void lock_semaphore() {}
void unlock_mutex() {}
void unlock_semaphore_ex() {}
void unlock_and_suspend() {}
void unlock_semaphore() {}
void spinunlock_and_suspend() {}
void sleep_on_sem() {}
void wakeup_sem() {}
void reset_semaphore() {}
void get_semaphore_info() {}
void get_semaphore_count() {}
void get_semaphore_owner() {}
void is_semaphore_locked() {}
void rwl_lock_read() {}
void rwl_lock_read_ex() {}
void rwl_lock_write() {}
void rwl_lock_write_ex() {}
void rwl_unlock_read() {}
void rwl_unlock_write() {}
void rwl_count_readers() {}
void rwl_count_all_readers() {}
void rwl_count_writers() {}
void rwl_count_all_writers() {}
void alloc_tld() {}
void free_tld() {}
void get_tld_addr() {}
void kmalloc() {}
void __kfree() {}
void alloc_real() {}
void free_real() {}
void get_free_page() {}
void get_free_pages() {}
void free_pages() {}
void flush_tlb() {}
void flush_tlb_global() {}
void flush_tlb_page() {}
void get_page_desc() {}
void get_swap_info() {}
void protect_dos_mem() {}
void unprotect_dos_mem() {}
void dup_swap_page() {}
void free_swap_page() {}
void set_page_directory_base_reg() {}
void alloc_area_list() {}
void create_area() {}
void delete_area() {}
void resize_area() {}
void remap_area() {}
void get_area_info() {}
void get_area_physical_address() {}
void memcpy_to_user() {}
void memcpy_from_user() {}
void strncpy_from_user() {}
void strcpy_to_user() {}
void get_next_area() {}
void get_vnode() {}
void put_vnode() {}
void flush_inode() {}
void set_inode_deleted_flag() {}
void get_inode_deleted_flag() {}
void open() {}
void close() {}
void based_open() {}
void write() {}
void write_pos() {}
void writev() {}
void writev_pos() {}
void read() {}
void read_pos() {}
void readv() {}
void readv_pos() {}
void readlink() {}
void freadlink() {}
void stat() {}
void fstat() {}
void lseek() {}
void chdir() {}
void fchdir() {}
void ioctl() {}
void mkdir() {}
void based_mkdir() {}
void rmdir() {}
void based_rmdir() {}
void unlink() {}
void based_unlink() {}
void sys_mount() {}
void sys_initialize_fs() {}
void symlink() {}
void based_symlink() {}
void sys_unmount() {}
void iterate_directory() {}
void get_directory_path() {}
void notify_node_monitors() {}
void create_device_node() {}
void delete_device_node() {}
void rename_device_node() {}
void get_empty_block() {}
void get_cache_block() {}
void mark_blocks_dirty() {}
void set_blocks_info() {}
void write_logged_blocks() {}
void release_cache_block() {}
void read_phys_blocks() {}
void write_phys_blocks() {}
void cached_read() {}
void cached_write() {}
void flush_device_cache() {}
void flush_locked_device_cache() {}
void flush_cache_block() {}
void setup_device_cache() {}
void shutdown_device_cache() {}
void decode_disk_partitions() {}
void alloc_pkt_buffer() {}
void reserve_pkt_header() {}
void free_pkt_buffer() {}
void init_net_queue() {}
void delete_net_queue() {}
void enqueue_packet() {}
void remove_head_packet() {}
void setsockopt() {}
void getsockopt() {}
void socket() {}
void closesocket() {}
void shutdown() {}
void getpeername() {}
void getsockname() {}
void connect() {}
void bind() {}
void listen() {}
void accept() {}
void recvmsg() {}
void sendmsg() {}
void recvfrom() {}
void sendto() {}
void send_packet() {}
void dispatch_net_packet() {}
void ip_send() {}
void ip_send_via() {}
void ip_in() {}
void add_net_interface() {}
void del_net_interface() {}
void acquire_net_interface() {}
void get_net_interface() {}
void find_interface() {}
void find_interface_by_addr() {}
void release_net_interface() {}
void get_interface_address() {}
void get_interface_broadcast() {}
void get_interface_destination() {}
void get_interface_netmask() {}
void get_interface_mtu() {}
void get_interface_flags() {}
void set_interface_address() {}
void set_interface_broadcast() {}
void set_interface_destination() {}
void set_interface_netmask() {}
void set_interface_mtu() {}
void set_interface_flags() {}
void add_route() {}
void del_route() {}
void ip_acquire_route() {}
void ip_find_route() {}
void ip_find_device_route() {}
void ip_find_static_route() {}
void ip_release_route() {}
void format_ipaddress() {}
void parse_ipaddress() {}
void find_module_by_address() {}
void get_boot_module_count() {}
void get_boot_module() {}
void put_boot_module() {}
void get_kernel_arguments() {}
void get_str_arg() {}
void get_num_arg() {}
void get_bool_arg() {}
void __const_udelay() {}
void __udelay() {}
void __ctype_flags() {}
void __ctype_tolower() {}
void __ctype_toupper() {}
void atol() {}
void bcopy() {}
void memcmp() {}
void qsort() {}
void sprintf() {}
void stricmp() {}
void strlcat() {}
void strlcpy() {}
void strnicmp() {}
void strpbrk() {}
void strspn() {}
void strstr() {}
void strtok() {}
void strtol() {}
void strtoul() {}
void vsprintf() {}
void MArray_Destroy() {}
void MArray_GetNextIndex() {}
void MArray_GetObj() {}
void MArray_GetPrevIndex() {}
void MArray_Init() {}
void MArray_Insert() {}
void MArray_Remove() {}
void make_port_public() {}
void make_port_private() {}
void find_port() {}
void get_msg_x() {}
void send_msg_x() {}
void get_port_from_handle() {}
void sys_get_msg() {}
void sys_delete_port() {}
void sys_send_msg() {}
void seed() {}
void rand() {}
void write_kernel_config_entry_header() {}
void write_kernel_config_entry_data() {}
void read_kernel_config_entry() {}
void register_device() {}
void unregister_device() {}
void claim_device() {}
void release_device() {}
void set_device_data() {}
void get_device_data() {}
void get_device_info() {}
void register_busmanager() {}
void get_busmanager() {}
void disable_device() {}
void disable_device_on_bus() {}
void enable_devices_on_bus() {}
void enable_all_devices() {}
void suspend_devices() {}
void resume_devices() {}
void ioport_root_resource() {}
void memory_root_resource() {}
void request_resource() {}
void ____request_resource() {}
void release_resource() {}
void allocate_resource() {}
void insert_resource() {}
void adjust_resource() {}
void __request_region() {}
void __release_region() {}
void nls_conv_cp_to_utf8() {}
void nls_conv_utf8_to_cp() {}
